from __future__ import annotations

from typing import Any, Protocol

from workspace.models import Task, TaskFilters, User


class UserRepositoryProtocol(Protocol):
    def find_by_username(self, username: str) -> User | None: ...
    def find_by_id(self, user_id: int) -> User | None: ...
    def list_active(self) -> list[User]: ...
    def list_all(self) -> list[User]: ...
    def save(self, user: User) -> User: ...


class TaskRepositoryProtocol(Protocol):
    def find_by_id(self, task_id: int) -> Task | None: ...
    def find_all(self, filters: TaskFilters | None = None) -> list[Task]: ...
    def save(self, task: Task) -> Task: ...
    def delete(self, task_id: int) -> None: ...
    def record_completion(self, task: Task, completed_by: int, scheduled_for: str | None) -> Task: ...
    def completion_history(self, limit: int = 200) -> list[dict[str, object]]: ...


class ContentRepositoryProtocol(Protocol):
    entity_type: str
    def find_by_id(self, entity_id: int) -> dict[str, Any] | None: ...
    def find_all(self, text: str = "", category: str = "", tag: str = "") -> list[dict[str, Any]]: ...
    def save(self, values: dict[str, Any], entity_id: int | None = None) -> dict[str, Any]: ...
    def delete(self, entity_id: int) -> None: ...


class ActivityRepositoryProtocol(Protocol):
    def add(self, user_id: int | None, action: str, entity_type: str, entity_id: int | None,
            title: str, details: str = "") -> None: ...

